export const SET_POSTINGS = "SET_POSTINGS";
export const LOADING_POSTINGS = "LOADING_POSTINGS";

export const SET_LIKED_POSTINGS = "SET_LIKED_POSTINGS";

export const CHANGE_CURRENT_FILTERS = "CHANGE_CURRENT_FILTERS";
export const SET_FILTERED_POSTINGS = "SET_FILTERED_POSTINGS";

export const SET_SEARCH_STRING = "SET_SEARCH_STRING";

export const GENERIC_ERROR = "GENERIC_ERROR";
